config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/users/sign_up",  :to => "jobs#index"
  end
  devise_for :users
  root 'jobs#index'

  authenticate :user do
    scope "/admin" do
      resources :companies
    end
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  mount_uploader :logo,        ImageUploader
  mount_uploader :intro_image, IntroImageUploader
  mount_uploader :css,         CssUploader
  
  validates :name,        presence: true
  validates :title,       presence: true
  validates :description, presence: true
  validates :about,       presence: true
  validates :footer_about, presence: true
  validates :address1,    presence: true
  validates :city,        presence: true
  validates :zip,         presence: true, length: { is: 5 }
  has_many   :users
  belongs_to :state
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :companies
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        flash[:success] = "Successfully added a new company: #{@company.name}"
        format.html { redirect_to companies_path }
      else
        flash[:danger] = "Sorry, unable to add a new company"
        format.html { render action: 'new' }
      end
    end
  end

  def edit
    @company =  Company.find(params[:id])
  end

  def update
    @company =  Company.find(params[:id])
    respond_to do |format| 
      if @company.update(company_params)
        flash[:success] = "Successfully updated the view contents for company: #{@company.name}"
        format.html { redirect_to companies_path }
      else
        flash[:danger] = "Sorry, unable to update the view contents for the company: #{@company.name}"
        format.html { render action: 'edit' }
      end
    end
  end

  def index
    @companies = Company.all
    @default_company =  Company.find_by(default: 'true')
  end

  def destroy
    @company = Company.find(params[:id])
    respond_to do |format|
      if @company.destroy
        flash[:success] = "Successfully deleted a company: #{@company.name}"
        format.html { redirect_to companies_path }
      else
        flash[:danger] = "Sorry, unable to delete the company"
        format.html { redirect_to companies_path }
      end
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :title, :description, :about, :address1, :address2, :city, 
      :state_id, :zip, :facebook, :google_plus, :twitter, :linkedin, :logo, :logo_cache, 
      :intro_image, :intro_image_cache, :css, :css_cache, :footer_about)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  layout "home"
  def index
    # The line below to load a company is not supposed to be like that, so later when we have 
    # the User model setup and once associted with Company then the line will change to 
    # @company = @current_user.company
    @company = Company.find_by(default: 'true')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "3sixD"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_edit_form.html.erb
<%= form_for (@company), :html => {:class => "form-horizontal center"} do |f| %>
  <div class="form-group"> 
    <%= f.label :name, "Company name:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :name, required: true, class: "form-control" %>
    </div>
    <%= f.label :title, "Company title:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :title, required: true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :address1, "Company address1:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :address1, required: true, class: "form-control" %>
    </div>
    
    <%= f.label :address2, "Company address2:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :address2, class: "form-control" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :city, "City:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :city, required: true, class: "form-control" %>
    </div>
    
    <%= f.label :state, "State:", class: "col-md-2 control-label" %>
    <div class="col-md-1">
      <%= f.collection_select :state_id, State.all, :id, :code, class: "form-control" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :zip, "Zip code:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :zip, required: true, class: "form-control" %>
    </div>
    
    <%= f.label :facebook, "Facebook account:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :facebook, class: "form-control" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :google_plus, "Google plus:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :google_plus, class: "form-control" %>
    </div>
    <%= f.label :twitter, "Twitter account:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :twitter, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :linkedin, "Linkedin account:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :linkedin, class: "form-control" %>
    </div>
    <%= f.label :about, "Company about:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_area :about, required: true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :description, "Company tagline:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_area :description, required: true, class: "form-control" %>
    </div>
    <%= f.label :footer_about, "Footer about:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_area :footer_about, required: true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :logo, "Company Logo:", class: "col-md-2 control-label" %>
    <div class="col-md-4">    
      <%= f.file_field :logo %>
      <%= f.hidden_field :logo_cache %>
    </div>
    <%= f.label :intro_image, "Company Image:", class: "col-md-2 control-label" %>
    <div class="col-md-4">    
      <%= f.file_field :intro_image %>
      <%= f.hidden_field :intro_image_cache %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :css, "Custom CSS:", class: "col-md-2 control-label" %>
    <div class="col-md-4">    
      <%= f.file_field :css %>
      <%= f.hidden_field :css_cache %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.button :submit, class: 'btn btn-primary', data: { :disable_with => "Saving..." } do %>
        <span><i class="fa fa-clock-o"></i></span>
        Update Company
      <% end %>
    </div>
  </div>
<% end %>

app/views/companies/_form.html.erb
<%= form_for (@company), :html => { multipart: true, :class => "form-horizontal center" } do |f| %>
  <div class="form-group"> 
    <%= f.label :name, "Company name:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :name, required: true, class: "form-control", placeholder: "Palmer" %>
    </div>
    <%= f.label :title, "Company title:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :title, required: true, class: "form-control", 
        placeholder: "Palmer Tech" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :address1, "Company address1:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :address1, required: true, class: "form-control", 
        placeholder: "700 Craighead St" %>
    </div>
    
    <%= f.label :address2, "Company address2:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :address2, class: "form-control", placeholder: "Suite 106" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :city, "City:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :city, required: true, class: "form-control", 
        placeholder: "Nashville" %>
    </div>
    
    <%= f.label :state, "State:", class: "col-md-2 control-label" %>
    <div class="col-md-1">
      <%= f.collection_select :state_id, State.all, :id, :code, class: "form-control" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :zip, "Zip code:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :zip, required: true, class: "form-control", 
        placeholder: "37204" %>
    </div>
    
    <%= f.label :facebook, "Facebook account:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :facebook, class: "form-control", placeholder: "https://facebook.com/palmer" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :google_plus, "Google plus:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :google_plus, class: "form-control", 
        placeholder: "https://plus.google.com/palmer" %>
    </div>
    <%= f.label :twitter, "Twitter account:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :twitter, class: "form-control", placeholder: "https://twitter.com/palmer" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :linkedin, "Linkedin account:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :linkedin, class: "form-control", 
        placeholder: "https://www.linkedin.com/palmer" %>
    </div>
    <%= f.label :about, "Company about:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_area :about, required: true, class: "form-control",
        placeholder: "Palmer Tech is one of the best leading tech companies in USA with over 500 millions of customers worldwide, one of the best place to explore tech" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :description, "Company tagline:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_area :description, required: true, class: "form-control", 
        placeholder: "Best Technologies Choices - With best products - For better life" %>
    </div>
    <%= f.label :footer_about, "Footer about:", class: "col-md-2 control-label" %>
    <div class="col-md-4">
      <%= f.text_area :footer_about, required: true, class: "form-control", 
        placeholder: "3sixD posts jobs for the positions which they are currently hiring" %>
    </div>
  </div>
  <div class="form-group"> 
    <%= f.label :logo, "Company Logo:", class: "col-md-2 control-label" %>
    <div class="col-md-4">    
      <%= f.file_field :logo %>
      <%= f.hidden_field :logo_cache %>
    </div>
    <%= f.label :intro_image, "Company Image:", class: "col-md-2 control-label" %>
    <div class="col-md-4">    
      <%= f.file_field :intro_image %>
      <%= f.hidden_field :intro_image_cache %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :css, "Custom CSS:", class: "col-md-2 control-label" %>
    <div class="col-md-4">    
      <%= f.file_field :css %>
      <%= f.hidden_field :css_cache %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.button :submit, class: 'btn btn-primary', data: { :disable_with => "Saving..." } do %>
        <span><i class="fa fa-clock-o"></i></span>
        Add Company
      <% end %>
    </div>
  </div>
<% end %>

app/views/companies/edit.html.erb
<% provide(:title, "Updating company info") %>
<div class="row">
  <div class="col-md-12 text-center">
    <h4>Provide your company details in a form below</h4>
    <hr class="star-primary"><br/>
    <%= render "edit_form" %>
  </div>
</div>

app/views/companies/index.html.erb
<% provide(:title, "All companies") %>
<div class="row">
  <div class="col-md-12">
    <h4 class="text-center">Subscribed Companies Details</h4>
    <hr class="star-primary"><br/>
	<div class="row">
	  <div class="col-md-12">
	  	<div class="add-company-button">
	  	  <%= link_to "Add new company", new_company_path, class: "btn btn-success" %>
	  	</div><br/><br/>
	  </div>
	  <div class="col-md-12">
	  <div class="panel panel-default">
	    <div class="table-responsive">
	      <table class="table table-bordered table-hover table-heading">
	        <thead>
	          <tr class="success">
	            <th class="text-center">Company Name</th>
	            <th class="text-center">Title</th>
	            <th class="text-center">Address</th>
	            <th class="text-center">City</th>
	            <th class="text-center">State</th>
	            <th class="text-center">Zip</th>
	            <th class="text-center">Actions</th>
	          </tr>
	        </thead>
	        <tbody class="companies-tab-pane">
	          <% @companies.each do |company| %>
	            <tr class="text-center">
	              <td><%= company.name %></td>
	              <td><%= company.title %></td>
	              <td><%= company.address1 %></td>
	              <td><%= company.city %></td>
	              <td><%= company.state.code %></td>
	              <td><%= company.zip %></td>   
	              <td>
	                <%= link_to "Edit", edit_company_path(company), 
	                    class: "btn btn-sm btn-default" %> |
	                <%= link_to "Delete", company_path(company), method: :delete, data: { confirm: 
	                    "Are you sure you want to delete the company: #{company.name}? click on OK to delete or Cancel to terminate the process" }, 
	                     class: "btn btn-sm btn-danger" %>
	              </td>
	            </tr>
	          <% end %>
	        </tbody>
	      </table>
	    </div>
	  </div></div>
	</div>
  </div>
</div>

app/views/companies/new.html.erb
<% provide(:title, "Add a new company") %>
<div class="row">
  <div class="col-md-12 text-center">
    <h4>Provide your company details in a form below</h4>
    <hr class="star-primary"><br/>
    <%= render "form" %>
  </div>
</div>

app/views/jobs/index.html.erb
<% provide(:title, 'Home') %>
<div id="job-openings">
  <script type="text/javascript" id="rbox-loader-script">
    if(!window._rbox){
    _rbox = { host_protocol:document.location.protocol, ready:function(cb){this.onready=cb;} };
    (function(d, e) {
      var s, t, i, src=['/static/client-src-served/widget/16028/rbox_api.js', '/static/client-src-served/widget/16028/rbox_impl.js'];
      t = d.getElementsByTagName(e); t=t[t.length - 1];
      for(i=0; i<src.length; i++) {
          s = d.createElement(e); s.src = _rbox.host_protocol + '//w.recruiterbox.com' + eval("src" + String.fromCharCode(91) + String(i) + String.fromCharCode(93));
          t.parentNode.insertBefore(s, t.nextSibling);
      }})(document, 'script');
    }
  </script>
</div>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <% if @default_company.present? && @default_company.logo.present? %>
        <%= link_to root_path do %>
          <%= image_tag (@default_company.logo_url(:thumb)), :class => "navbar-brand", :alt => "Company logo" %>
        <% end %>
      <% else %>
        <%= link_to root_path do %>
          <%= image_tag "3sixd.png", :class => "navbar-brand", :alt => "Company logo" %>
        <% end %>
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li class="page-scroll">
          <a href="#job">Jobs</a>
        </li>
        <li class="page-scroll">
          <a href="#about">About</a>
        </li>
        <li class="page-scroll">
          <a href="#contact">Contact</a>
        </li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Add company', new_company_path %>
              </li>
              <li>
                <%= link_to 'Customize company', companies_path %>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Change your password', edit_user_registration_path %>
              </li>
              <li>
                <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="index" id="<%= user_signed_in? ? 'page-top' : 'unsigned-in-users-page' %>">
  <% if user_signed_in? %>
    <%= render 'layouts/header' %>
    <section>
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <div class="container">
        <div class="row" id="application-layout">
          <%= yield %>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                      <h3>Location</h3>
                      <% if current_page?(companies_path) %>
                        <p>
                          <%= @default_company.title %><br><%= @default_company.address1 %>
                          <% if @default_company.address2.present? %>
                            <br><%= @default_company.address2 %>
                          <% end %>
                          <br><%= @default_company.city %>, <%= @default_company.state.code %> <%= @default_company.zip %>
                        </p>
                      <% elsif current_page?(new_company_path) %>
                        <p>Company name<br>Address1 <br>Address2 <br>City, state zip code</p>
                      <% elsif @company.present? && !(current_page?(new_company_path)) %>
                        <p>
                          <%= @company.title %><br><%= @company.address1 %>
                          <% if @company.address2.present? %>
                            <br><%= @company.address2 %>
                          <% end %>
                          <br><%= @company.city %>, <%= @company.state.code %> <%= @company.zip %>
                        </p>
                      <% end %>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                              <% if current_page?(companies_path) %>
                                <a href="<%= @default_company.facebook %>" class="btn-social btn-outline"
                                  target="_blank"><i class="fa fa-fw fa-facebook"></i>
                                </a>
                              <% elsif current_page?(new_company_path) %>
                                <a href="#" class="btn-social btn-outline">
                                  <i class="fa fa-fw fa-facebook"></i>
                                </a>
                              <% elsif @company.present? && !(current_page?(new_company_path)) %>
                                <a href="<%= @company.facebook %>" class="btn-social btn-outline"
                                  target="_blank"><i class="fa fa-fw fa-facebook"></i>
                                </a>
                              <% end %>
                            </li>
                            <li>
                              <% if current_page?(companies_path) %>
                                <a href="<%= @default_company.google_plus %>" class="btn-social btn-outline" target="_blank"><i class="fa fa-fw fa-google-plus"></i>
                                </a>
                              <% elsif current_page?(new_company_path) %>
                                <a href="#" class="btn-social btn-outline">
                                  <i class="fa fa-fw fa-google-plus"></i>
                                </a>
                              <% elsif @company.present? && !(current_page?(new_company_path)) %>
                                <a href="<%= @company.google_plus %>" class="btn-social btn-outline"
                                  target="_blank"><i class="fa fa-fw fa-google-plus"></i>
                                </a>
                              <% end %>
                            </li>
                            <li>
                              <% if current_page?(companies_path) %>
                                <a href="<%= @default_company.twitter %>" class="btn-social btn-outline"
                                  target="_blank"><i class="fa fa-fw fa-twitter"></i>
                                </a>
                              <% elsif current_page?(new_company_path) %>
                                <a href="#" class="btn-social btn-outline">
                                  <i class="fa fa-fw fa-twitter"></i>
                                </a>
                              <% elsif @company.present? && !(current_page?(new_company_path)) %>
                                <a href="<%= @company.twitter %>" class="btn-social btn-outline"
                                  target="_blank"><i class="fa fa-fw fa-twitter"></i>
                                </a>
                              <% end %>
                            </li>
                            <li>
                              <% if current_page?(companies_path) %>
                                <a href="<%= @default_company.linkedin %>" class="btn-social btn-outline"
                                  target="_blank"><i class="fa fa-fw fa-linkedin"></i>
                                </a>
                              <% elsif current_page?(new_company_path) %>
                                <a href="#" class="btn-social btn-outline">
                                  <i class="fa fa-fw fa-linkedin"></i>
                                </a>
                              <% elsif @company.present? && !(current_page?(new_company_path)) %>
                                <a href="<%= @company.linkedin %>" class="btn-social btn-outline"
                                  target="_blank"><i class="fa fa-fw fa-linkedin"></i>
                                </a>
                              <% end %>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                      <% if current_page?(companies_path) %>
                        <h3>About <%= @default_company.name %></h3>
                        <p><%= @default_company.footer_about %></p>
                      <% elsif current_page?(new_company_path) %>
                        <h3>About Company</h3>
                        <p>
                          Tell us more about your company by providing the details on the field footer about from the company's form
                        </p>
                      <% elsif @company.present? && !(current_page?(new_company_path)) %>
                        <h3>About <%= @company.name %></h3>
                        <p><%= @company.footer_about %></p>
                      <% end %>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        &copy; <%= Date.today.strftime("%Y") %>
                        <% if current_page?(companies_path) %>
                          <%= @default_company.name %>
                        <% elsif current_page?(new_company_path) %>
                          <%= 'Company' %>
                        <% elsif @company.present? && !(current_page?(new_company_path)) %>
                          <%= @company.name %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </footer>
  <% else %>
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    <section>
      <div class="container">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </section>
  <% end %>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll visible-xs visible-sm">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <!-- job Modals -->

    <!-- jQuery -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script> 

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
</body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>